name: flutter_github_actions
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter:
    uses-material-design: true
    assets:
      - assets/main/

scripts:
  launch-icon-setup: |
    dart pub add dev:flutter_launcher_icons:
    flutter pub get
  native-splash-setup: |
    dart pub add dev:flutter_native_splash:
    flutter pub get
  gen:
    launch-icon:
      main: dart run flutter_launcher_icons -f flutter_launcher_icons-main.yaml
      checkcircle: dart run flutter_launcher_icons -f flutter_launcher_icons-checkcircle.yaml
      star: dart run flutter_launcher_icons -f flutter_launcher_icons-star.yaml
      favorite: dart run flutter_launcher_icons -f flutter_launcher_icons-favorite.yaml
    native-splash:
      main: dart run flutter_native_splash:create --path=./native_splash_yml/flutter_native_splash-main.yaml --flavor main
      checkcircle: dart run flutter_native_splash:create --path=./native_splash_yml/flutter_native_splash-checkcircle.yaml --flavor checkcircle
      star: dart run flutter_native_splash:create --path=./native_splash_yml/flutter_native_splash-star.yaml --flavor star
      favorite: dart run flutter_native_splash:create --path=./native_splash_yml/flutter_native_splash-favorite.yaml --flavor favorite

