name: Build iOS IPA (Star Flavor) and Upload to Firebase

on:
  workflow_dispatch:

jobs:
  build-ios-star:
    runs-on: macos-latest
    env:
      CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      PROFILE_NAME: ${{ secrets.PROVISIONING_PROFILE_NAME_STAR }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_IOS_APP_ID_STAR }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Install Certificates
        run: |
         echo "$IOS_CERTIFICATE_STAR_BASE64" | base64 --decode > FIREBASE_DISTRIBUTION_IOS_CREDENTIAL_FILE_CONTENT.p12
         security create-keychain -p "" build.keychain
         
         security unlock-keychain -p "" ~/Library/Keychains/build.keychain
         security list-keychains -s ~/Library/Keychains/build.keychain
         security import FIREBASE_DISTRIBUTION_IOS_CREDENTIAL_FILE_CONTENT.p12 \
         -k ~/Library/Keychains/build.keychain \
         -P "$CERT_PASSWORD" \
         -T /usr/bin/codesign
         
         

      - name: Install Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ./profiles/star/*.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Flutter pub get
        run: flutter pub get

      - name: Build iOS App (Star Flavor)
        run: flutter build ios --flavor star -t main-star.dart --release --no-codesign

      - name: Archive with xcodebuild
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme star \
            -configuration star Release \
            -archivePath build/Runner.xcarchive archive \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME" \
            DEVELOPMENT_TEAM="$TEAM_ID"

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/Runner \
            -exportOptionsPlist ios/ExportOptions-star.plist

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Authenticate Firebase
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > serviceAccountKey.json

      - name: Upload IPA to Firebase App Distribution (Star Flavor)
        run: |
          firebase appdistribution:distribute build/Runner/Runner.ipa \
            --app "$FIREBASE_APP_ID" \
            --groups "beta-testers" \
            --token "$FIREBASE_SERVICE_ACCOUNT"

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Runner.ipa
          path: build/Runner/Runner.ipa
