name: Hello World

on:
  push:
    branches:
      - main   # runs on push to main branch
  pull_request: # also runs on PRs

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.5'
          # Enable caching: https://github.com/subosito/flutter-action?tab=readme-ov-file#caching
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - run: flutter pub get

      - name: Setup Main Keystore
        run: |
          mkdir -p android/keystore
          echo "$MAIN_KEYSTORE_BASE64" | base64 --decode > android/keystore/main.jks
          cat > android/signing.properties <<EOF
          release.storeFile=android/keystore/main.jks
          release.storePassword=$MAIN_KEYSTORE_PASSWORD
          release.keyAlias=$MAIN_KEY_ALIAS
          release.keyPassword=$MAIN_KEY_PASSWORD
          EOF
        env:
          MAIN_KEYSTORE_BASE64: ${{ secrets.MAIN_KEYSTORE_BASE64 }}
          MAIN_KEYSTORE_PASSWORD: ${{ secrets.MAIN_KEYSTORE_PASSWORD }}
          MAIN_KEY_ALIAS: ${{ secrets.MAIN_KEY_ALIAS }}
          MAIN_KEY_PASSWORD: ${{ secrets.MAIN_KEY_PASSWORD }}

      - name: Building Main Release APK
        run: echo "Will check later" #flutter build apk --release -t lib/main.dart

      - name: Building Main Release AAB
        run: echo "Will check later" #flutter build appbundle --release -t lib/main.dart

      - name: Setup Checkcircle Flavor Keystore
        run: |
#          mkdir -p android/keystore
          echo "$CHECKCIRCLE_KEYSTORE_BASE64" | base64 --decode > android/keystore/check-circle.jks
          cat > android/signing.properties <<EOF
          checkcircle.storeFile=android/keystore/check-circle.jks
          checkcircle.storePassword=$CHECKCIRCLE_KEYSTORE_PASSWORD
          checkcircle.keyAlias=$CHECKCIRCLE_KEY_ALIAS
          checkcircle.keyPassword=$CHECKCIRCLE_KEY_PASSWORD
          EOF
        env:
          CHECKCIRCLE_KEYSTORE_BASE64: ${{ secrets.CHECKCIRCLE_KEYSTORE_BASE64 }}
          CHECKCIRCLE_KEYSTORE_PASSWORD: ${{ secrets.CHECKCIRCLE_KEYSTORE_PASSWORD }}
          CHECKCIRCLE_KEY_ALIAS: ${{ secrets.CHECKCIRCLE_KEY_ALIAS }}
          CHECKCIRCLE_KEY_PASSWORD: ${{ secrets.CHECKCIRCLE_KEY_PASSWORD }}

      - name: Building Checkcircle Flavor Release APK
        run: flutter build apk --flavor checkcircle --release -t lib/main_checkcircle.dart

      - name: Building Checkcircle Flavor Release AAB
        run: flutter build appbundle --flavor checkcircle --release -t lib/main_checkcircle.dart

      - name: Setup Favorite Flavor Keystore
        run: |
          echo "$FAVORITE_KEYSTORE_BASE64" | base64 --decode > android/keystore/favorite.jks
          cat > android/signing.properties <<EOF
          favorite.storeFile=android/keystore/favorite.jks
          favorite.storePassword=$FAVORITE_KEYSTORE_PASSWORD
          favorite.keyAlias=$FAVORITE_KEY_ALIAS
          favorite.keyPassword=$FAVORITE_KEY_PASSWORD
          EOF
        env:
          FAVORITE_KEYSTORE_BASE64: ${{ secrets.FAVORITE_KEYSTORE_BASE64 }}
          FAVORITE_KEYSTORE_PASSWORD: ${{ secrets.FAVORITE_KEYSTORE_PASSWORD }}
          FAVORITE_KEY_ALIAS: ${{ secrets.FAVORITE_KEY_ALIAS }}
          FAVORITE_KEY_PASSWORD: ${{ secrets.FAVORITE_KEY_PASSWORD }}

      - name: Building Favorite Flavor Release APK
        run: flutter build apk --flavor favorite --release -t lib/main_favorite.dart

      - name: Building Favorite Flavor Release AAB
        run: flutter build appbundle --flavor favorite --release -t lib/main_favorite.dart

      - name: Setup Star Flavor Keystore
        run: |
          echo "$STAR_KEYSTORE_BASE64" | base64 --decode > android/keystore/star.jks
          cat > android/signing.properties <<EOF
          star.storeFile=android/keystore/star.jks
          star.storePassword=$STAR_KEYSTORE_PASSWORD
          star.keyAlias=$STAR_KEY_ALIAS
          star.keyPassword=$STAR_KEY_PASSWORD
          EOF
        env:
          STAR_KEYSTORE_BASE64: ${{ secrets.STAR_KEYSTORE_BASE64 }}
          STAR_KEYSTORE_PASSWORD: ${{ secrets.STAR_KEYSTORE_PASSWORD }}
          STAR_KEY_ALIAS: ${{ secrets.STAR_KEY_ALIAS }}
          STAR_KEY_PASSWORD: ${{ secrets.STAR_KEY_PASSWORD }}

      - name: Building Star Flavor Release APK
        run: flutter build apk --flavor star --release -t lib/main_star.dart

      - name: Building Star Flavor Release AAB
        run: flutter build appbundle --flavor star --release -t lib/main_star.dart
